[package]
name = "selenium-rs"
version = "0.1.0"
authors = ["saresend <saresend@usc.edu>"]

[dependencies]
reqwest = "0.8.7"
url = "1.7.1"
serde = "1.0.71"
serde_json = "1.0.26"
serde_derive = "1.0.71"
